# Generated by Django 3.1.6 on 2021-02-14 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=50, verbose_name="Artist's name")),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('jenre_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100, verbose_name="song's tilte")),
                ('composer', models.ManyToManyField(related_name='composer_name', to='ranges.Artist')),
                ('lyricist', models.ManyToManyField(related_name='lyricist_name', to='ranges.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 31, 20, 947795, tzinfo=utc))),
                ('latest_update', models.DateTimeField(auto_now=True, verbose_name='date update lately')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='ranges.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranges.genre')),
                ('highest_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_note', to='ranges.note')),
                ('lowest_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_note', to='ranges.note')),
                ('performer', models.ManyToManyField(related_name='performer_name', to='ranges.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='ranges.song')),
            ],
        ),
    ]
