# Generated by Django 3.1.6 on 2021-02-14 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='fake_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fake_note', to='ranges.note'),
        ),
        migrations.AlterField(
            model_name='range',
            name='highest_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_note', to='ranges.note'),
        ),
        migrations.AlterField(
            model_name='range',
            name='lowest_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_note', to='ranges.note'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 15, 23, 34, 327116, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='range',
            unique_together={('song', 'artist')},
        ),
    ]
