# Generated by Django 3.1.6 on 2021-02-14 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20210215_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='fake_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fake_note', to='ranges.note'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 15, 29, 26, 66966, tzinfo=utc)),
        ),
    ]
