# Generated by Django 3.1.6 on 2021-02-19 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0007_auto_20210217_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 12, 14, 29, 457754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
