# Generated by Django 3.1.6 on 2021-02-25 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0008_auto_20210219_2114'),
    ]


    atomic = False
    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('artist_name',)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('song_name',)},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='jenre_id',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='jenre_name',
            new_name='genre_name',
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 12, 21, 1, 573060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=100, verbose_name='Tilte'),
        ),
    ]
