# Generated by Django 3.1.6 on 2021-03-03 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0009_auto_20210225_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='origin',
            field=models.BooleanField(default=True, verbose_name='is_original'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 7, 58, 11, 365081, tzinfo=utc)),
        ),
    ]
