# Generated by Django 3.1.6 on 2021-03-03 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0010_auto_20210303_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Affiliation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_artist_Affiliation_+', to='ranges.Artist'),
        ),
        migrations.AlterField(
            model_name='range',
            name='origin',
            field=models.BooleanField(default=True, verbose_name='is original'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 9, 19, 5, 520639, tzinfo=utc)),
        ),
    ]
