# Generated by Django 3.1.6 on 2021-03-03 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0011_auto_20210303_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Affiliation',
        ),
        migrations.AddField(
            model_name='artist',
            name='affiliation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_artist_affiliation_+', to='ranges.Artist'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 10, 32, 48, 448710, tzinfo=utc)),
        ),
    ]
