# Generated by Django 3.1.6 on 2021-03-04 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0012_auto_20210303_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 13, 7, 13, 149982, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='range',
            unique_together={('song', 'artist', 'genre')},
        ),
    ]
