# Generated by Django 3.1.6 on 2021-03-07 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0014_auto_20210304_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='_artist_affiliation_+', to='ranges.Artist'),
        ),
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 12, 3, 6, 855072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='range',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.ManyToManyField(blank=True, related_name='arranger_name', to='ranges.Artist'),
        ),
    ]
