# Generated by Django 3.1.6 on 2021-03-07 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0015_auto_20210307_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 12, 4, 31, 83856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='range',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date released'),
        ),
    ]
